version: "3.7"
services:
  neo4j:
    image: neo4j:4.3.2
    restart: always
    hostname: neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
    environment:
      - NEO4J_AUTH=neo4j/letmein
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
  graphql:
    build:
      context: ./graphql
    hostname: graphql
    restart: always
    container_name: graphql
    ports:
      - 4000:4000
    links:
      - neo4j
    depends_on:
      - neo4j
  ui:
    build: ./ui
    container_name: ui
    ports:
      - 3000:3000
    environment:
      - REACT_APP_GRAPHQL_URI=http://localhost:4000/graphql
    links:
        - graphql
    depends_on:
      - graphql